- hosts: all
  gather_facts: no
  tasks:
     - name: generate hass curr_pass
       delegate_to: localhost
       command:  python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt('{{lookup('file', '/$HOME/password/pass.txt')}}')"
       register: pass

     - debug:
         var: pass.stdout

     - name: update password
       user:
         name: itopr
         password: '{{pass.stdout}}'
       become: yes
